### ISSUE TITLE
Class 'App\Press\TestCase'  not found

### ISSUE THREAD

**Issue by neocarvajal** [vicgonvt/Press#1]
Hi, i have the following error in Press/src/MarkdownParser.php 

![screenshot from 2019-03-04 11-13-37](https://user-images.githubusercontent.com/3886811/53742547-4582c200-3e6f-11e9-9a34-2abd8ff6ccc8.png)

My MarkdownParser.php is 

![screenshot from 2019-03-04 11-14-19](https://user-images.githubusercontent.com/3886811/53742575-58959200-3e6f-11e9-8c7b-60b8a3c7af67.png)

How can I solve that?

**Comment by vicgonvt** [comment]
Your MarkdownParser should not be extending the TestCase. Check out the source code here

https://github.com/vicgonvt/Press/blob/master/src/MarkdownParser.php
