### ISSUE TITLE
project limitations

### ISSUE THREAD

**Issue by roni-estein** [vicgonvt/Press#3]
Hey, I was searching for a tiny clean customizable markdown powered blog to add to a laravel project instead hand rolling one or pulling in something like vuepress. Would this be terrible in production? Based on the intro video it looks like exactly what I'm looking for. Any idea of why you wouldn't want to use this?

**Comment by vicgonvt** [comment]
I use it in production. It’s great.

**Comment by roni-estein** [comment]
Thanks, I'll give it a go, 

I think you should remove or change the wording on here. We all need to GROK packages we pull in. But I think this section dissuades people from giving it a chance. Essentially saying its a "teaching only" tool.

In Progress
Be warned, this source code and course is for educational purposes only and may not be production ready. Use at your own risk.

**Comment by roni-estein** [comment]
Wow I listened to that play list while working and it was one of the best screen casts I’ve even heard.

I’d point out one thing, as beneficial; you never talk about versioning or tagging and pulling it in from composer once you deploy a project using this package. I’ve really struggled with extracting functionality to packages, and running through updating them, semver etc...

Now I found this project from the markdown angle. But since it’s such a great package course I’d recommend adding that in.

That being said this is fabulous. Thanks

**Comment by roni-estein** [comment]
Oh I thought of one more package oriented issue that I’ve run into that you may have also run into. Adding global functions to a project for example the laravel dd() function through your package. And finally restricting those functions to a namespace. So having a global function that runs only in Test namespace.

I end up doing some magic from the local composer.json however I’m sure it can be accomplished from the package.

Cheers and thanks again
